### ISSUE TITLE
No longer works in Brave

### ISSUE THREAD

**Issue by joecampo** [OpenDyslexic/extension#46]
Hi there,

Please feel free to close as I know this extension is specifically for Chrome; however, after after the recent update it no longer works in Brave (and it previously did).

Not sure if there is a direction you could point me in that would help me better debug.

Version: 1.27.111 Chromium: 92.0.4515.131 (Official Build) (x86_64)

Thanks for the awesome extension :)

**Comment by RobertJGabriel** [comment]
Hey @joecampo,

Great news! The new version is now up and running, and it'll be released this weekend. Thanks for your support and patience!

Cheers,
Robert James
