### ISSUE TITLE
No longer works after update on 8th.

### ISSUE THREAD

**Issue by MrJDucky** [OpenDyslexic/extension#52]
Plugin no longer changes the font of the text in the browser after latest update.

Toggling off/on does not fix.

Toggling the plugin on, it adds this to the <head>
`<link rel="stylesheet" type="text/css" id="opendyslexic-regular" href="chrome-extension://cdnapgfjopgaggbmfgbiinmmbdcglnam/assets/styles/core/opendyslexic-opendyslexic-regular.css">`

When I go to that href URL gives me:

> Your file couldn’t be accessedIt may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND

Also getting this in the console:
> Denying load of chrome-extension://cdnapgfjopgaggbmfgbiinmmbdcglnam/assets/styles/core/opendyslexic-opendyslexic-regular.css. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
content.js:1          GET chrome-extension://invalid/ net::ERR_FAILED

**Never mind, apparently switching from regular to bold back to regular fixed it.**

**Comment by RobertJGabriel** [comment]
Hey,

Thank you for reporting, closing as its fixed now and we have a new version coming with tests to ensure this doesn't happen again.

Thank you
Robert James Gabriel

**Comment by blin** [comment]
Hi Robert, I just installed "OpenDyslexic for Chrome 40.1.0" for the first time, and I do not observe any change to the font, any suggestions on how I can debug this?
