### ISSUE TITLE
@ sign is tiny

### ISSUE THREAD

**Issue by MrJDucky** [OpenDyslexic/extension#65]
Plugin update happened and now the @ sign is TINY and now checking all the other !"£$^%&(*&^ type of signs look weird as well. Like they've been drawn with an extra thin pen. Ew. Numbers also look different to me, but I could be wrong. Not sure I enjoy this change. How do I revert D:

! " £ $ % ^ & * ( ) @

![image](https://github.com/OpenDyslexic/extension/assets/6209681/9a4ae6fb-e97f-49c7-a6d0-3a31a4641546)

**Comment by RobertJGabriel** [comment]
Hey @MrJDucky 

Looking into this right now.

Will get a release out aspa.
