### ISSUE TITLE
OpenDyslexic 2024.6.8 is defaulting to ON

### ISSUE THREAD

**Issue by DanielGallop** [OpenDyslexic/extension#72]
With version 2024.6.8, webpages use the OpenDyslexic font by default. The toggle option in the extension settings needs to be enabled and then disabled to turn it off.

**Comment by pascallef** [comment]
We seem to have the same problem.
We had to remove it unfortunatly until this is resolved.

**Comment by RobertJGabriel** [comment]
@DanielGallop @pascallef 
Thank you for the heads up, I have submitted a new release to the store.

Will responded the moment its released.

**Comment by RobertJGabriel** [comment]
@DanielGallop @pascallef 

This is now fixed and released :)
