### ISSUE TITLE
Edge Extension link not working

### ISSUE THREAD

**Issue by coliff** [OpenDyslexic/extension#74]
The README link to the Edge extension is: https://microsoftedge.microsoft.com/addons/detail/opendyslexic/
However, that gives a 404 error.

**Comment by deadnamedimmer** [comment]
This issue also applies to the Firefox extension (https://addons.mozilla.org/en-US/firefox/addon/opendyslexic-for-firefox/). It seems like it has been removed from both the Firefox and Edge extension stores.

**Comment by RobertJGabriel** [comment]
Oh! Will get these updated this weekend.

**Comment by RobertJGabriel** [comment]
@coliff & @deadnamedimmer 

Just waiting on them to approve both. Will close this for now and will update the readme once I get the approval links.

**Comment by coliff** [comment]
This issue was closed as completed back in July but the extension still isn't on the Edge store at the link on the README. :-(  [microsoftedge.microsoft.com/addons/detail/opendyslexic](https://microsoftedge.microsoft.com/addons/detail/opendyslexic/)

Any news?

**Comment by RobertJGabriel** [comment]
Here you got https://microsoftedge.microsoft.com/addons/detail/opendyslexic-for-edge/foiljfndmiabdijmmagefnejggpfinej

Will update the readme, they changed the url links.

@coliff

**Comment by coliff** [comment]
> Here you got [microsoftedge.microsoft.com/addons/detail/opendyslexic-for-edge/foiljfndmiabdijmmagefnejggpfinej](https://microsoftedge.microsoft.com/addons/detail/opendyslexic-for-edge/foiljfndmiabdijmmagefnejggpfinej)
> 
> Will update the readme, they changed the url links.
> 
> @coliff

thanks! Downloaded it and rated it 5-stars :-)
